spring:
  jpa:
    show-sql: true
  datasource:
    hikari:
      jdbc-url: jdbc:postgresql://localhost:5432/agency
      maximum-pool-size: 20
      driver-class-name: org.postgresql.Driver
    username: postgres
    password: root
    url: jdbc:postgresql://localhost:5432/agency
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-description: Flyway Scripts
    locations: classpath:/db/migration
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    url: ${spring.datasource.url}
    default-schema: public
    validate-on-migrate: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: oluska92666@gmail.com
    password: fxfdlwnstazitijg
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
---
caffeine:
  initialCapacity: 30
  maximumSize: 1000
  expireAfterAccessHours: 12

---

page-capacity:
  company: 10
  deal: 4
  location: 15
  manager: 10
  person: 10
  real-estate: 8
  rent: 15
  sale: 15


---




